config/routes.rb
Rails.application.routes.draw do
  resources :products
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'

  # get '/products/:id', to 'products#show'#, as 'product' Para mostrar un producto, el alias es product
  get '/products/:id/edit', to: 'products#edit' #, as 'edit_product'

  patch '/product/:id', to: 'products#update' #Es el equivalente a put
  put '/product/:id', to: 'products#update' #Es el equivalente a put
  
  delete 'product/:id', to: 'products#delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
            if @product.save
                redirect_to products_path # Helper, cosas que vienen pre-definidas en rails
            else
                render:new
            end
    end
    
    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to products_path
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end

    private
        def product_params
            params.require(:product).permit(:name, :description, :price) # Metodos privados a los que no tiene acceso la aplicacion, solo se va a tener acceso aqui adentro
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1> Editar un producto </h1>

<%= form_for @product do |f| %>

<div>
	
	<%= f.label :name %>
	<%= f.text_field :name %>

</div>

<div>
	<%= f.label :description %>
	<%= f.text_area :description %>
</div>

<div>
	<%= f.label :price %>
	<%= f.number_field :price %>
</div>

<div>
	<%= f.submit %>
</div>

<% end %>

app/views/products/index.html.erb
<h1> Productos </h1>

<table>
	<tr>
		<thead>
			<th>
				Nombre
			</th>
			<th>
				Descripcion
			</th>
			<th>
				Precio
			</th>
		</thead>
	</tr>

    <% @products.each do |producto| %>
	<tr>
		<td><%= producto.name %></td>
		<td><%= producto.description %></td>
		<td><%= producto.price %></td>
        <td>
        <%= link_to "Editar", edit_product_path(producto) %>
        <%= link_to "Eliminar", producto, method: :delete, data: {confirm: "¿Seguro que quieres borrar?"} %>
        </td>
    </tr>
    <%end%>

</table>

app/views/products/new.html.erb
<h1> Agregar Nuevo Producto </h1>

<%= form_for @product do |f| %>

<div>
	
	<%= f.label :name %>
	<%= f.text_field :name %>

</div>

<div>
	<%= f.label :description %>
	<%= f.text_area :description %>
</div>

<div>
	<%= f.label :price %>
	<%= f.number_field :price %>
</div>

<div>
	<%= f.submit %>
</div>

<% end %>